### ISSUE TITLE
Adding an index to the status for faster retrieval

### ISSUE THREAD

**Issue by karllhughes** [spatie/laravel-model-status#20]
Hey spatie team,
Love y'all's Laravel work. Any interest or thought on indexing the status column? Is that something you want to leave to users to do or should this package implement it?

I'm just concerned that looking up my model by status could get slow if I have lots of statuses.

**Comment by freekmurze** [comment]
Thanks for your kind words and your suggestion. We're going to leave things as they are for now.

Users can easily add an index in their own projects.

**Comment by shez1983** [comment]
but i think you should add the index in your migration file.. why? because most people would not be aware of this and you want to show 'best practices'.. also one less thing for the user :) 

but again thanks for the awesome packages...  (while i am here, I would also state that tehre should be  a migration table example ie whats created in your README.. i can do a pull request when I install it in my own laravel project if you havent done so already)

**Comment by ahoiroman** [comment]
Hi there,

as I am just a little curious: Which column should have that index? I'd guess on the `model_id`?
